version: "3"
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - vaultnet
    environment:
      MYSQL_ROOT_PASSWORD: dbpasswd
      MYSQL_DATABASE: vault
      MYSQL_USER: vault
      MYSQL_PASSWORD: vaultdbpasswd
  etcd:
    image: etcd:latest
    build: ./etcd
    networks:
      - vaultnet
  vault:
    image: vault:latest
    build: ./vault
    ports:
      - "8200:8200"
    networks:
      - vaultnet
    depends_on:
      - mariadb
      - etcd
    cap_add:
      - IPC_LOCK
networks:
  vaultnet:
volumes:
  db-data:
